### ISSUE TITLE
csv writing

### ISSUE THREAD

**Issue by ILeftTheLaw** [calthoff/self_taught#4]
I input the following code from http://tinyurl.com/go8wepf:
```
import csv
with open("st.csv", "w") as f:
    write = csv.writer(f, delimiter=",")
    write.writerow(["one",
                    "two",
                    "three"])
    write.writerow(["four",
                    "five",
                    "six"])
```

When I open the st.csv file in Microsoft Excel, one, two and three appear as they should on row 1, but four, five and six appear on row 3, not row 2.

This also happened when I first used the code in the example from the book (Kindle location 3107) that used the syntax w.writerow(["one", . . . etc. instead of the above syntax.

As I barely have a grasp of what I'm coding here, I'm not sure why the output file differs in its description from the book.

Not trying to be a pain, just trying to understand what I'm learning.

**Comment by calthoff** [comment]
@ILeftTheLaw No problem! Please feel free to ask as many questions as you want. I am here to help. By the way, have you joined the Self-Taught Programmers Facebook group yet? It would be great to see you there:https://www.facebook.com/groups/selftaughtprogrammers/. I will look into this now.

**Comment by calthoff** [comment]
@ILeftTheLaw Thank for pointing this out. I made a mistake. Sorry about that! A computer science teacher actually emailed me with the solution:

In Chapter 9: Files, you go over how to create a CSV file with python using the code (python_ex234.py from your github):

import csv


        with open("st.csv", "w") as f:
        write = csv.writer(f, delimiter=",")
        write.writerow(["one",
        "two",
        "three"])
        write.writerow(["four",
        "five",
        "six"])

And then state that this will create a CSV file, when opened with Excel (or some other equivalent) with the words one, two and three in row one, and words four, five and six in row two. But because Python 3 adds a new line character to the at the end of the writerow method, the words four, five and six actually appear on row three.

In order to fix this you need to add the parameter newline = '' to the open method. Your code should look like this:

import csv


        with open("st.csv", "w", newline='') as f:
        write = csv.writer(f, delimiter=",")
        write.writerow(["one",
        "two",
        "three"])
        write.writerow(["four",
        "five",
.       "six"])

**Comment by ILeftTheLaw** [comment]
Many thanks, @calthoff !
