### ISSUE TITLE
SyntaxError: multiple statements found while compiling a single statement

### ISSUE THREAD

**Issue by Mtaylor777** [calthoff/self_taught#6]
Just bought book, first day of programming. "Hello World" worked fine, but every time I type something more complex, I get the "SyntaxError: multiple statements found while compiling a single statement". Have tried copying and pasting from website and still get this error. Please help.

home = "America"
if home == "America":
    print("Hello, America!")
else:
    print("Hello, World!")
    
SyntaxError: multiple statements found while compiling a single statement

**Comment by calthoff** [comment]
@Mtaylor777 Hey there. It looks like you are copying and pasting code into the shell, which you cannot do. You need to paste it into IDLE.

**Comment by ZeezyW** [comment]
I am having this same issue, but it is not due to copy and pasting. Any time I enter code into the shell that is more than one command (sorry for the beginner terminology) I get this error. For example:

colors = ["purple", "orange", "green"]

guess = input("Guess a color:")

if guess in colors:
    print("You guessed correctly!")
else:
    print("Wrong! Try again.")

I can enter the "colors" line on it's own, or i can enter the "guess" line on its own, but when I try to do both at the same time, or add the if clause to the end. I get this error. It looks to me as if I'm following the spacing in the book.

**Comment by calthoff** [comment]
@ZeezyW Hey there. Try typing your code into a new IDLE window, saving your program, and running it instead of using the shell.
